use crate::{
    config::capitalize_first_letter, render_template_with_cursor, CommandConfig, Config,
    ConfigError, HotkeyConfig, KeyChord, MatchMode, Matcher, TextInjector,
};
use std::{
    collections::VecDeque,
    io::Read,
    process::{Command, Stdio},
    sync::mpsc,
    thread,
    time::{Duration, Instant},
};

const MAX_RESULTS_PER_EVENT: usize = 1024;
const MAX_RESULT_BYTES_PER_EVENT: usize = 4 * 1024 * 1024;
const MAX_COMMAND_OUTPUT_BYTES: usize = 1024 * 1024;

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum InputEvent {
    Text(String),
    /// A normalized key press. Backends should emit this before any text
    /// event generated by the same physical key.
    Key(KeyChord),
    Backspace,
    Boundary,
    /// Changes capture policy for the focused surface. Sensitive fields must
    /// disable matching and clear any text already buffered. This is a
    /// compositor/backend signal, not a user action (use `PauseChanged` for that).
    FocusChanged {
        sensitive: bool,
    },
    /// User-initiated pause/resume of text expansion. Independent from
    /// `FocusChanged`: both conditions disable capture when active.
    /// Resuming does not re-enable capture if still in a sensitive field.
    PauseChanged(bool),
    /// Reports which application is now focused, for `app_filter`-scoped
    /// expansions. `None` means unknown (no window tracker running, or the
    /// compositor does not support one) -- app-restricted expansions fail
    /// closed in that case rather than matching everywhere.
    WindowChanged(Option<WindowContext>),
}

/// The focused window's identity, as reported by a window tracker backend.
/// Both fields are best-effort and compositor-dependent: a toplevel may
/// expose an app id but not a title, or vice versa.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct WindowContext {
    pub app_id: Option<String>,
    pub title: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExpansionResult {
    pub trigger: String,
    pub erase_chars: usize,
    pub insert: String,
    /// Characters to move the cursor left after `insert` is typed, from a
    /// `{{cursor}}` marker in the replacement. `None`/`Some(0)` leave the
    /// cursor at the end, matching every replacement written before this
    /// existed.
    pub cursor_offset: Option<usize>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct HotkeyResult {
    pub chord: KeyChord,
    pub description: String,
    pub command: CommandConfig,
}

#[derive(Debug, thiserror::Error)]
pub enum ExpansionError {
    #[error("injection failed: {0}")]
    Injection(#[from] crate::InjectorError),
}

#[derive(Debug, thiserror::Error)]
pub enum HotkeyError {
    #[error("could not start hotkey action")]
    Spawn(#[source] std::io::Error),
    #[error("hotkey action timed out after {0} ms")]
    Timeout(u64),
    #[error("hotkey action failed with status {0}")]
    Failed(String),
}

pub struct ExpansionEngine {
    config: Config,
    matcher: Matcher,
    matcher_indices: Vec<usize>,
    buffer: VecDeque<char>,
    max_buffer_chars: usize,
    /// Set whenever the buffer evicts a character from the front because it
    /// exceeded `max_buffer_chars`, and cleared only by `buffer.clear()`
    /// (a known boundary, e.g. after a match). Lets `match_allowed`
    /// distinguish "truly at the start of input" from "a preceding
    /// character existed but was evicted" -- the two cases an empty
    /// `rev().nth(length)` cannot tell apart on its own.
    buffer_truncated: bool,
    /// User-initiated pause state. Independent from sensitive field detection.
    user_paused: bool,
    /// Compositor/backend signal that focused field is sensitive (password,
    /// OTP, etc.). Independent from user_paused.
    sensitive_focus: bool,
    command_cache: Vec<Option<CommandCacheEntry>>,
    hotkeys: Vec<(KeyChord, usize)>,
    current_window: Option<WindowContext>,
    undo_chord: Option<KeyChord>,
    /// The most recent successful expansion, kept only until the very next
    /// event of any other kind (see `process`): `(text to type back,
    /// characters to erase)`. Not set for a result with a `{{cursor}}`
    /// marker, since undoing after the user has typed more text at that
    /// repositioned cursor has no single well-defined "erase N characters
    /// backward" meaning.
    last_expansion: Option<(String, usize)>,
}

#[derive(Debug, Clone)]
struct CommandCacheEntry {
    expires_at: Instant,
    value: String,
}

impl ExpansionEngine {
    pub fn new(config: Config) -> Result<Self, ConfigError> {
        config.validate()?;
        // Triggers match literally (see `Matcher`, a case-sensitive char
        // trie), so a `propagate_case` expansion is matched by inserting
        // its uppercase and capitalized forms as additional trigger
        // strings mapped to the same config entry, rather than by making
        // matching itself case-insensitive (which would affect every
        // expansion, not just ones that opted in). `take_match` later reads
        // back which form was actually typed to decide how to case the
        // replacement. `effective_triggers()` is the single source of
        // truth for this expansion -- `validate()` (called just above)
        // checks collisions across the exact same variants, so a config
        // that reaches this point is already known not to have two
        // expansions competing for the same matcher entry.
        let enabled: Vec<(usize, String)> = config
            .expansion
            .iter()
            .enumerate()
            .filter(|(_, entry)| entry.enabled)
            .flat_map(|(index, entry)| {
                entry
                    .effective_triggers()
                    .into_iter()
                    .map(move |trigger| (index, trigger))
            })
            .collect();
        let matcher_indices = enabled.iter().map(|(index, _)| *index).collect();
        let matcher = Matcher::new(enabled.into_iter().map(|(_, trigger)| trigger));
        let max_buffer_chars = config.settings.max_buffer_chars;
        // `validate()` above already confirmed this parses; a config that
        // fails to load is never used to construct an engine.
        let undo_chord = config
            .settings
            .undo_chord
            .as_deref()
            .and_then(|chord| KeyChord::parse(chord).ok());
        let command_cache = vec![None; config.expansion.len()];
        let hotkeys = config
            .hotkey
            .iter()
            .enumerate()
            .filter(|(_, binding)| binding.enabled)
            .filter_map(|(index, binding)| {
                KeyChord::parse(&binding.chord)
                    .ok()
                    .map(|chord| (chord, index))
            })
            .collect();
        Ok(Self {
            config,
            matcher,
            matcher_indices,
            buffer: VecDeque::new(),
            max_buffer_chars,
            buffer_truncated: false,
            user_paused: false,
            sensitive_focus: false,
            command_cache,
            hotkeys,
            current_window: None,
            undo_chord,
            last_expansion: None,
        })
    }

    /// The currently known focused window, if any. Used to carry window
    /// context across a config reload: reload replaces the whole engine
    /// (parse-then-swap), which would otherwise silently forget the last
    /// known window until the next real focus change -- wrongly
    /// fail-closing `app_filter`-scoped expansions for a window the user
    /// never actually left.
    pub fn current_window(&self) -> Option<&WindowContext> {
        self.current_window.as_ref()
    }

    /// Restores window context captured via `current_window` before this
    /// engine replaced a previous one. Does not clear the match buffer,
    /// matching `InputEvent::WindowChanged`'s own behavior (see its
    /// handler for why that clear is unnecessary).
    pub fn set_current_window(&mut self, window: Option<WindowContext>) {
        self.current_window = window;
    }

    /// Whether text expansion capture is currently enabled.
    /// Both user pause and sensitive field focus independently disable capture.
    fn is_capture_enabled(&self) -> bool {
        !self.user_paused && !self.sensitive_focus
    }

    /// Resolve a normalized key chord into configured actions. This method is
    /// side-effect free; the daemon or script runtime owns execution policy,
    /// cancellation, and capability checks.
    pub fn process_key(&self, chord: &KeyChord) -> Vec<HotkeyResult> {
        if !self.is_capture_enabled() {
            return Vec::new();
        }
        self.hotkeys
            .iter()
            .filter(|(configured, _)| configured.matches(chord))
            .filter_map(|(_, index)| {
                let binding: &HotkeyConfig = self.config.hotkey.get(*index)?;
                Some(HotkeyResult {
                    chord: chord.clone(),
                    description: binding.description.clone(),
                    command: binding.command.clone(),
                })
            })
            .collect()
    }

    /// If `chord` matches the configured `settings.undo_chord` and an
    /// undoable expansion is still pending (see `last_expansion`), consumes
    /// it and returns the `ExpansionResult` that reverts it: erase what was
    /// inserted, type the original trigger back. The caller applies this
    /// exactly like a normal expansion (`ExpansionEngine::apply`). Returns
    /// `None` if undo is unconfigured, paused, the chord doesn't match, or
    /// nothing is pending to undo.
    pub fn try_undo(&mut self, chord: &KeyChord) -> Option<ExpansionResult> {
        if !self.is_capture_enabled() {
            return None;
        }
        if !self.undo_chord.as_ref()?.matches(chord) {
            return None;
        }
        let (restore_text, erase_chars) = self.last_expansion.take()?;
        Some(ExpansionResult {
            trigger: String::new(),
            erase_chars,
            insert: restore_text,
            cursor_offset: None,
        })
    }

    /// Execute one validated hotkey action without invoking a shell. Output
    /// is discarded and the process is bounded by the configured timeout.
    pub fn execute_hotkey(result: &HotkeyResult) -> Result<(), HotkeyError> {
        let mut child = Command::new(&result.command.program)
            .args(&result.command.args)
            .stdin(Stdio::null())
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .spawn()
            .map_err(HotkeyError::Spawn)?;
        let deadline = Instant::now() + Duration::from_millis(result.command.timeout_ms);
        loop {
            match child.try_wait() {
                Ok(Some(status)) if status.success() => return Ok(()),
                Ok(Some(status)) => {
                    return Err(HotkeyError::Failed(status.to_string()));
                }
                Ok(None) if Instant::now() < deadline => thread::sleep(Duration::from_millis(5)),
                Ok(None) => {
                    let _ = child.kill();
                    let _ = child.wait();
                    return Err(HotkeyError::Timeout(result.command.timeout_ms));
                }
                Err(error) => {
                    let _ = child.kill();
                    let _ = child.wait();
                    return Err(HotkeyError::Spawn(error));
                }
            }
        }
    }

    /// Process an event stream. A text event may contain multiple Unicode
    /// scalar values; matching is performed after each one.
    pub fn process(&mut self, event: InputEvent) -> Vec<ExpansionResult> {
        // A pending undo is valid only immediately after the expansion it
        // would revert, with no other event in between. `InputEvent::Key`
        // is exempt: it never touches the buffer or produces a result here
        // (see below), and is how the undo chord itself arrives -- clearing
        // on it would make undo impossible to ever trigger.
        if !matches!(event, InputEvent::Key(_)) {
            self.last_expansion = None;
        }
        match event {
            InputEvent::Key(_) => Vec::new(),
            InputEvent::Text(text) => {
                let mut results = Vec::new();
                let mut result_bytes = 0usize;
                if !self.is_capture_enabled() {
                    return results;
                }
                for character in text.chars() {
                    let pending = self.matcher.find_suffix(self.buffer.iter().rev().copied());
                    if let Some((index, length)) = pending {
                        if let Some(config_index) = self.matcher_indices.get(index).copied() {
                            let trigger = &self.config.expansion[config_index].trigger;
                            if !self.matcher.can_continue(trigger, character) {
                                let trailing_word_character = self.config.expansion[config_index]
                                    .match_mode
                                    == MatchMode::WordBoundary
                                    && is_word_character(character);
                                if !trailing_word_character {
                                    if let Some(result) = self.take_match(config_index, length) {
                                        let bytes = result
                                            .trigger
                                            .len()
                                            .saturating_add(result.insert.len());
                                        if results.len() >= MAX_RESULTS_PER_EVENT
                                            || result_bytes.saturating_add(bytes)
                                                > MAX_RESULT_BYTES_PER_EVENT
                                        {
                                            self.clear_buffer();
                                            break;
                                        }
                                        result_bytes = result_bytes.saturating_add(bytes);
                                        results.push(result);
                                    }
                                }
                            }
                        }
                    }
                    if results.len() >= MAX_RESULTS_PER_EVENT {
                        self.clear_buffer();
                        break;
                    }
                    self.buffer.push_back(character);
                    while self.buffer.len() > self.max_buffer_chars {
                        self.buffer.pop_front();
                        self.buffer_truncated = true;
                    }
                    if let Some((index, length)) =
                        self.matcher.find_suffix(self.buffer.iter().rev().copied())
                    {
                        let config_index = self.matcher_indices.get(index).copied();
                        let Some(config_index) = config_index else {
                            self.clear_buffer();
                            continue;
                        };
                        let (trigger, match_mode, propagate_case) = {
                            let expansion = &self.config.expansion[config_index];
                            (
                                expansion.trigger.clone(),
                                expansion.match_mode,
                                expansion.propagate_case,
                            )
                        };
                        // The actually-typed suffix, which may be an
                        // uppercase or capitalized variant of `trigger` for
                        // a `propagate_case` expansion (see
                        // `ExpansionEngine::new`): `has_continuation` must
                        // be checked against what was typed, since that is
                        // the string actually present in the forward trie,
                        // not necessarily `trigger` itself.
                        let typed: String = {
                            let start = self.buffer.len().saturating_sub(length);
                            self.buffer.iter().skip(start).collect()
                        };
                        if self.matcher.has_continuation(&typed)
                            || match_mode == MatchMode::WordBoundary
                        {
                            continue;
                        }
                        if !self.match_allowed(config_index, length) {
                            continue;
                        }
                        let Ok((mut insert, cursor_offset)) = self.render_expansion(config_index)
                        else {
                            self.clear_buffer();
                            continue;
                        };
                        if propagate_case {
                            insert = apply_case_style(&typed, &insert);
                        }
                        let expansion_bytes = trigger.len().saturating_add(insert.len());
                        if result_bytes.saturating_add(expansion_bytes) > MAX_RESULT_BYTES_PER_EVENT
                        {
                            self.clear_buffer();
                            break;
                        }
                        result_bytes = result_bytes.saturating_add(expansion_bytes);
                        if cursor_offset.is_none() {
                            self.last_expansion = Some((typed.clone(), insert.chars().count()));
                        }
                        results.push(ExpansionResult {
                            trigger,
                            erase_chars: length,
                            insert,
                            cursor_offset,
                        });
                        // Do not allow a replacement to combine with the
                        // next typed text and accidentally trigger again.
                        self.clear_buffer();
                    }
                }
                results
            }
            InputEvent::Backspace => {
                self.buffer.pop_back();
                Vec::new()
            }
            InputEvent::Boundary => {
                let result = self
                    .matcher
                    .find_suffix(self.buffer.iter().rev().copied())
                    .and_then(|(index, length)| {
                        self.matcher_indices
                            .get(index)
                            .copied()
                            .and_then(|config_index| self.take_match(config_index, length))
                    });
                self.clear_buffer();
                result.into_iter().collect()
            }
            InputEvent::FocusChanged { sensitive } => {
                self.sensitive_focus = sensitive;
                self.clear_buffer();
                Vec::new()
            }
            InputEvent::PauseChanged(paused) => {
                self.user_paused = paused;
                self.clear_buffer();
                Vec::new()
            }
            InputEvent::WindowChanged(window) => {
                // The text in the buffer belongs to the previously-focused
                // application. Text expansion state must be scoped to the
                // focused window, not to the desktop session. Even if
                // app_filter would correctly re-evaluate against the new
                // window, the physical characters in the buffer are from the
                // old application and must not be used to compute replacements
                // for the new one. This prevents cross-window trigger matches
                // that can cause unrelated text deletion.
                self.current_window = window;
                self.clear_buffer();
                Vec::new()
            }
        }
    }

    fn take_match(&mut self, config_index: usize, length: usize) -> Option<ExpansionResult> {
        if !self.match_allowed(config_index, length) {
            return None;
        }
        let trigger = self.config.expansion[config_index].trigger.clone();
        let propagate_case = self.config.expansion[config_index].propagate_case;
        // Read the actually-typed trigger text (which may be an uppercase
        // or capitalized variant registered in the matcher for this entry;
        // see `ExpansionEngine::new`) before it is popped off below. Needed
        // both for case propagation and as the text an undo restores.
        let typed: String = {
            let start = self.buffer.len().saturating_sub(length);
            self.buffer.iter().skip(start).collect()
        };
        let (mut insert, cursor_offset) = self.render_expansion(config_index).ok()?;
        if propagate_case {
            insert = apply_case_style(&typed, &insert);
        }
        for _ in 0..length {
            self.buffer.pop_back();
        }
        if cursor_offset.is_none() {
            self.last_expansion = Some((typed, insert.chars().count()));
        }
        Some(ExpansionResult {
            trigger,
            erase_chars: length,
            insert,
            cursor_offset,
        })
    }

    /// Renders an expansion's text and, for a plain (non-command-backed)
    /// template containing a `{{cursor}}` marker, the number of characters
    /// from the end of the rendered text the cursor should land at.
    /// Command output is used verbatim -- it is not hand-authored per
    /// invocation the way a template is, so `{{cursor}}` is not recognized
    /// in it.
    fn render_expansion(&mut self, config_index: usize) -> Result<(String, Option<usize>), ()> {
        let expansion = &self.config.expansion[config_index];
        let Some(command) = &expansion.command else {
            return render_template_with_cursor(
                &expansion.replacement,
                &crate::TemplateContext::system(),
            )
            .map_err(|_| ());
        };
        if command.cache_ms > 0 {
            if let Some(entry) = self.command_cache[config_index].as_ref() {
                if entry.expires_at > Instant::now() {
                    return Ok((entry.value.clone(), None));
                }
            }
        }
        let value = run_command(command).map_err(|_| ())?;
        if command.cache_ms > 0 {
            self.command_cache[config_index] = Some(CommandCacheEntry {
                expires_at: Instant::now() + Duration::from_millis(command.cache_ms),
                value: value.clone(),
            });
        }
        Ok((value, None))
    }

    /// Resets the matcher buffer to a known boundary. Always use this
    /// instead of `self.buffer.clear()` directly: it also clears
    /// `buffer_truncated`, since a fresh boundary means whatever preceded it
    /// is no longer relevant to word-boundary checks.
    fn clear_buffer(&mut self) {
        self.buffer.clear();
        self.buffer_truncated = false;
    }

    fn match_allowed(&self, config_index: usize, length: usize) -> bool {
        let expansion = &self.config.expansion[config_index];
        if !self.app_filter_allows(expansion) {
            return false;
        }
        if expansion.match_mode != MatchMode::WordBoundary {
            return true;
        }
        match self.buffer.iter().rev().nth(length) {
            Some(character) => !is_word_character(*character),
            // A `None` here is ambiguous unless we know nothing was ever
            // evicted: it means either "this is genuinely the start of
            // input" (allow) or "a preceding character existed but was
            // truncated out of the buffer" (unknown -- fail closed).
            None => !self.buffer_truncated,
        }
    }

    /// An expansion with an empty `app_filter` matches everywhere. A
    /// non-empty filter requires a known focused window whose app id or
    /// title contains one of the filter substrings (case-insensitive); if
    /// window tracking is unavailable, this fails closed rather than
    /// matching unconditionally.
    fn app_filter_allows(&self, expansion: &crate::ExpansionConfig) -> bool {
        if expansion.app_filter.is_empty() {
            return true;
        }
        let Some(window) = &self.current_window else {
            return false;
        };
        expansion.app_filter.iter().any(|filter| {
            let filter = filter.to_lowercase();
            window
                .app_id
                .as_deref()
                .is_some_and(|id| id.to_lowercase().contains(&filter))
                || window
                    .title
                    .as_deref()
                    .is_some_and(|title| title.to_lowercase().contains(&filter))
        })
    }

    /// Apply an expansion. Backends may perform the replacement atomically;
    /// simple backends use the safe erase-then-insert default.
    pub fn apply<I: TextInjector + ?Sized>(
        injector: &mut I,
        result: &ExpansionResult,
    ) -> Result<(), ExpansionError> {
        injector.replace(&result.trigger, &result.insert)?;
        // Best-effort: a `{{cursor}}` marker's placement failing (or being
        // unsupported by this backend) does not mean the expansion itself
        // failed, since the replacement text above was already inserted.
        if let Some(offset) = result.cursor_offset.filter(|offset| *offset > 0) {
            let _ = injector.move_cursor_left(offset);
        }
        Ok(())
    }
}

fn is_word_character(character: char) -> bool {
    character.is_alphanumeric() || character == '_'
}

/// Recases `text` (a rendered replacement) to match the casing pattern of
/// `typed` (the trigger as the user actually typed it), for expansions with
/// `propagate_case` enabled. A single capitalized letter or a capitalized
/// word yields a capitalized replacement; two or more uppercase letters
/// yield a fully uppercased replacement; anything else (typed as
/// configured, or mixed case) leaves the replacement unchanged.
fn apply_case_style(typed: &str, text: &str) -> String {
    let letters: Vec<char> = typed
        .chars()
        .filter(|character| character.is_alphabetic())
        .collect();
    match letters.as_slice() {
        [] => text.to_owned(),
        [single] if single.is_uppercase() => capitalize_first_letter(text),
        letters if letters.iter().all(|character| character.is_uppercase()) => text.to_uppercase(),
        [first, ..] if first.is_uppercase() => capitalize_first_letter(text),
        _ => text.to_owned(),
    }
}

/// Why a command-backed expansion's configured program did not produce
/// usable output. Kept narrow (no raw OS error strings) since this can be
/// surfaced to the GUI/CLI, not just logged internally.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CommandError {
    /// The program could not be started at all (not found, not executable,
    /// permission denied, ...).
    SpawnFailed,
    /// The program did not exit within `command.timeout_ms` and was killed.
    Timeout,
    /// The program exited but reported failure.
    NonZeroExit(Option<i32>),
    /// Output exceeded the bounded size this engine will buffer.
    OutputTooLarge,
    /// Output was not valid UTF-8.
    InvalidUtf8,
    /// The output-reading thread did not report back in time (should not
    /// happen once the process itself has exited; treated as a distinct
    /// case rather than folded into `Timeout` since it points at a bug in
    /// the reader thread, not a slow command).
    OutputChannelLost,
}

impl std::fmt::Display for CommandError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CommandError::SpawnFailed => write!(f, "could not start the program"),
            CommandError::Timeout => write!(f, "timed out before it produced output"),
            CommandError::NonZeroExit(Some(code)) => write!(f, "exited with status {code}"),
            CommandError::NonZeroExit(None) => write!(f, "was terminated by a signal"),
            CommandError::OutputTooLarge => write!(
                f,
                "produced more than {} bytes of output",
                MAX_COMMAND_OUTPUT_BYTES
            ),
            CommandError::InvalidUtf8 => write!(f, "produced output that was not valid UTF-8"),
            CommandError::OutputChannelLost => write!(f, "output could not be read back"),
        }
    }
}

impl std::error::Error for CommandError {}

/// Runs a command-backed expansion's configured program to completion and
/// returns its trimmed stdout. Public so the GUI/CLI can invoke it directly
/// for an explicit, user-initiated "run once" preview -- callers must never
/// invoke this from a rendering/repaint loop, since it spawns a real process
/// with real side effects on every call.
pub fn run_command(command: &CommandConfig) -> Result<String, CommandError> {
    let mut child = Command::new(&command.program)
        .args(&command.args)
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|_| CommandError::SpawnFailed)?;
    let stdout = child.stdout.take().ok_or(CommandError::SpawnFailed)?;
    let (sender, receiver) = mpsc::sync_channel(1);
    thread::spawn(move || {
        let mut bytes = Vec::new();
        let result = stdout
            .take((MAX_COMMAND_OUTPUT_BYTES + 1) as u64)
            .read_to_end(&mut bytes)
            .map(|_| bytes);
        let _ = sender.send(result);
    });

    let deadline = Instant::now() + Duration::from_millis(command.timeout_ms);
    let status = loop {
        match child.try_wait() {
            Ok(Some(status)) => break status,
            Ok(None) if Instant::now() < deadline => thread::sleep(Duration::from_millis(5)),
            Ok(None) => {
                let _ = child.kill();
                let _ = child.wait();
                return Err(CommandError::Timeout);
            }
            Err(_) => {
                let _ = child.kill();
                let _ = child.wait();
                return Err(CommandError::Timeout);
            }
        }
    };
    if !status.success() {
        return Err(CommandError::NonZeroExit(status.code()));
    }
    let bytes = receiver
        .recv_timeout(Duration::from_millis(100))
        .map_err(|_| CommandError::OutputChannelLost)?
        .map_err(|_| CommandError::OutputChannelLost)?;
    if bytes.len() > MAX_COMMAND_OUTPUT_BYTES {
        return Err(CommandError::OutputTooLarge);
    }
    let output = String::from_utf8(bytes).map_err(|_| CommandError::InvalidUtf8)?;
    Ok(output.trim_end_matches(['\r', '\n']).to_owned())
}

#[cfg(test)]
mod tests {
    use std::os::unix::fs::PermissionsExt;

    use super::*;

    fn engine() -> ExpansionEngine {
        ExpansionEngine::new(
            Config::parse(
                r#"
            [[expansion]]
            trigger = ":hello"
            replacement = "Hello from Wayland!"

            [[expansion]]
            trigger = ":cafe"
            replacement = "café ☕"
        "#,
            )
            .unwrap(),
        )
        .unwrap()
    }

    #[test]
    fn expands_unicode_replacement() {
        let mut engine = engine();
        let result = engine
            .process(InputEvent::Text(":cafe".into()))
            .pop()
            .unwrap();
        assert_eq!(result.erase_chars, 5);
        assert_eq!(result.insert, "café ☕");
    }

    #[test]
    fn app_filtered_expansion_fails_closed_without_window_tracking() {
        let config = Config::parse(
            r#"
            [[expansion]]
            trigger = ":sig"
            replacement = "Regards"
            app_filter = ["thunderbird"]
        "#,
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let mut results = engine.process(InputEvent::Text(":sig".into()));
        results.extend(engine.process(InputEvent::Boundary));
        assert!(
            results.is_empty(),
            "app-restricted expansion must not fire without a known focused window"
        );
    }

    #[test]
    fn app_filtered_expansion_matches_by_app_id_case_insensitively() {
        let config = Config::parse(
            r#"
            [[expansion]]
            trigger = ":sig"
            replacement = "Regards"
            app_filter = ["Thunderbird"]
        "#,
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        engine.process(InputEvent::WindowChanged(Some(WindowContext {
            app_id: Some("org.mozilla.thunderbird".into()),
            title: None,
        })));
        let mut results = engine.process(InputEvent::Text(":sig".into()));
        results.extend(engine.process(InputEvent::Boundary));
        assert_eq!(results.pop().unwrap().insert, "Regards");
    }

    #[test]
    fn current_window_can_be_carried_across_a_replacement_engine() {
        // Simulates what a config reload must do: a fresh `ExpansionEngine`
        // starts with no window context, which would otherwise wrongly
        // fail-close every `app_filter`-scoped expansion until the next
        // real focus change even though the user's window never changed.
        let config = Config::parse(
            r#"
            [[expansion]]
            trigger = ":sig"
            replacement = "Regards"
            app_filter = ["thunderbird"]
        "#,
        )
        .unwrap();
        let mut old_engine = ExpansionEngine::new(config.clone()).unwrap();
        old_engine.process(InputEvent::WindowChanged(Some(WindowContext {
            app_id: Some("org.mozilla.thunderbird".into()),
            title: None,
        })));

        let mut new_engine = ExpansionEngine::new(config).unwrap();
        assert!(new_engine.current_window().is_none());
        new_engine.set_current_window(old_engine.current_window().cloned());

        let mut results = new_engine.process(InputEvent::Text(":sig".into()));
        results.extend(new_engine.process(InputEvent::Boundary));
        assert_eq!(results.pop().unwrap().insert, "Regards");
    }

    #[test]
    fn app_filtered_expansion_ignores_other_windows() {
        let config = Config::parse(
            r#"
            [[expansion]]
            trigger = ":sig"
            replacement = "Regards"
            app_filter = ["thunderbird"]
        "#,
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        engine.process(InputEvent::WindowChanged(Some(WindowContext {
            app_id: Some("org.kde.konsole".into()),
            title: Some("konsole".into()),
        })));
        let mut results = engine.process(InputEvent::Text(":sig".into()));
        results.extend(engine.process(InputEvent::Boundary));
        assert!(results.is_empty());
    }

    #[test]
    fn unfiltered_expansion_matches_regardless_of_window_tracking() {
        let mut engine = engine();
        let mut results = engine.process(InputEvent::Text(":hello".into()));
        results.extend(engine.process(InputEvent::Boundary));
        assert_eq!(results.pop().unwrap().insert, "Hello from Wayland!");
    }

    #[test]
    fn window_changed_clears_buffer_to_prevent_cross_window_matches() {
        // Text expansion state must be scoped to the focused window, not the
        // desktop session. The buffer contains characters typed in the previous
        // application, so clearing on window change prevents cross-window
        // trigger matches that could erase unrelated text.
        let mut engine = engine();
        engine.process(InputEvent::Text(":hel".into()));
        engine.process(InputEvent::WindowChanged(Some(WindowContext {
            app_id: Some("org.kde.kate".into()),
            title: None,
        })));
        let mut results = engine.process(InputEvent::Text("lo".into()));
        results.extend(engine.process(InputEvent::Boundary));
        // The buffer was cleared on window change, so ":hello" was never formed
        assert!(
            results.is_empty(),
            "cross-window partial triggers must not continue matching"
        );
    }

    #[test]
    fn cross_window_trigger_does_not_delete_wrong_text() {
        // Regression test for P0 bug: Alt-Tab mid-trigger.
        // Type ":he" in App A, switch to App B, type "llo". Should NOT match.
        let config = Config::parse(
            r#"
            [[expansion]]
            trigger = ":hello"
            replacement = "expansion result"
        "#,
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();

        // Type partial trigger in first window
        engine.process(InputEvent::Text(":he".into()));

        // Switch windows
        engine.process(InputEvent::WindowChanged(Some(WindowContext {
            app_id: Some("org.kde.konsole".into()),
            title: None,
        })));

        // Complete what looks like the trigger in the new window
        let mut results = engine.process(InputEvent::Text("llo".into()));
        results.extend(engine.process(InputEvent::Boundary));

        assert!(
            results.is_empty(),
            "expansion must not fire for cross-window text sequences"
        );
    }

    #[test]
    fn unfiltered_expansion_after_window_change() {
        // Verify that unfiltered expansions still work after a window change,
        // just with a fresh buffer (no cross-window text combination).
        let mut engine = engine();
        engine.process(InputEvent::WindowChanged(Some(WindowContext {
            app_id: Some("org.kde.kate".into()),
            title: None,
        })));
        let mut results = engine.process(InputEvent::Text(":hello".into()));
        results.extend(engine.process(InputEvent::Boundary));
        assert_eq!(results.pop().unwrap().insert, "Hello from Wayland!");
    }

    #[test]
    fn pause_changed_disables_capture_and_clears_buffer() {
        let mut engine = engine();
        engine.process(InputEvent::Text(":hel".into()));
        engine.process(InputEvent::PauseChanged(true));
        // Capture disabled, buffer cleared
        let results = engine.process(InputEvent::Text("lo".into()));
        assert!(results.is_empty(), "paused engine must not produce expansions");
    }

    #[test]
    fn pause_changed_resume_re_enables_capture() {
        let mut engine = engine();
        // Pause
        engine.process(InputEvent::PauseChanged(true));
        let results = engine.process(InputEvent::Text(":hello".into()));
        assert!(results.is_empty(), "paused engine must not expand");

        // Resume
        engine.process(InputEvent::PauseChanged(false));
        let mut results = engine.process(InputEvent::Text(":hello".into()));
        results.extend(engine.process(InputEvent::Boundary));
        assert_eq!(
            results.pop().unwrap().insert,
            "Hello from Wayland!",
            "resumed engine must expand"
        );
    }

    #[test]
    fn sensitive_focus_and_pause_are_independent() {
        // P0 security fix: resume must not re-enable capture if in sensitive field
        let mut engine = engine();

        // 1. Enter sensitive field (password input)
        engine.process(InputEvent::FocusChanged { sensitive: true });
        assert!(
            engine.process(InputEvent::Text(":hello".into())).is_empty(),
            "must not expand in sensitive field"
        );

        // 2. User pauses (independently)
        engine.process(InputEvent::PauseChanged(true));

        // 3. User resumes (independently)
        engine.process(InputEvent::PauseChanged(false));

        // 4. Should still be disabled because sensitive field is still active!
        let results = engine.process(InputEvent::Text(":hello".into()));
        assert!(
            results.is_empty(),
            "resume must not re-enable capture while still in sensitive field"
        );

        // 5. Leave sensitive field
        engine.process(InputEvent::FocusChanged { sensitive: false });

        // 6. Now expansion works
        let mut results = engine.process(InputEvent::Text(":hello".into()));
        results.extend(engine.process(InputEvent::Boundary));
        assert_eq!(results.pop().unwrap().insert, "Hello from Wayland!");
    }

    #[test]
    fn dispatches_enabled_hotkey_actions_without_side_effects() {
        let config = Config::parse(
            r#"
            [[hotkey]]
            chord = "Ctrl+Alt+M"
            description = "Open meeting helper"
            [hotkey.command]
            program = "/bin/true"
            timeout_ms = 100
            "#,
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let chord = KeyChord::parse("control+option+m").unwrap();
        let result = engine.process_key(&chord);
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].chord.to_string(), "Ctrl+Alt+M");
        assert_eq!(result[0].description, "Open meeting helper");
        assert_eq!(result[0].command.program, "/bin/true");

        engine.process(InputEvent::FocusChanged { sensitive: true });
        assert!(engine.process_key(&chord).is_empty());

        engine.process(InputEvent::FocusChanged { sensitive: false });
        assert!(engine.process_key(&chord).len() == 1);

        engine.process(InputEvent::PauseChanged(true));
        assert!(engine.process_key(&chord).is_empty());

        engine.process(InputEvent::PauseChanged(false));
        assert!(engine.process_key(&chord).len() == 1);
    }

    #[test]
    fn hotkey_actions_use_direct_execution_and_timeout() {
        let config = Config::parse(
            r#"
            [[hotkey]]
            chord = "Ctrl+M"
            [hotkey.command]
            program = "/bin/true"
            timeout_ms = 100
            "#,
        )
        .unwrap();
        let engine = ExpansionEngine::new(config).unwrap();
        let action = engine
            .process_key(&KeyChord::parse("Ctrl+M").unwrap())
            .pop()
            .unwrap();
        ExpansionEngine::execute_hotkey(&action).unwrap();
    }

    #[test]
    fn command_expansion_uses_direct_program_output() {
        let config = Config::parse(
            r#"
            [[expansion]]
            trigger = ":kernel"
            replacement = ""
            [expansion.command]
            program = "/bin/printf"
            args = ["kernel-6.1"]
            timeout_ms = 500
        "#,
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let result = engine
            .process(InputEvent::Text(":kernel".into()))
            .pop()
            .unwrap();
        assert_eq!(result.insert, "kernel-6.1");
    }

    #[test]
    fn command_expansion_times_out_without_blocking_forever() {
        let config = Config::parse(
            r#"
            [[expansion]]
            trigger = ":slow"
            replacement = ""
            [expansion.command]
            program = "/bin/sleep"
            args = ["1"]
            timeout_ms = 10
        "#,
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert!(engine.process(InputEvent::Text(":slow".into())).is_empty());
    }

    #[test]
    fn command_expansion_cache_reuses_recent_output() {
        let counter =
            std::env::temp_dir().join(format!("wayexpand-command-cache-{}", std::process::id()));
        std::fs::write(&counter, "0").unwrap();
        let script = format!(
            "n=$(cat '{}'); n=$((n+1)); printf '%s' \"$n\" > '{}'; printf '%s' \"$n\"",
            counter.display(),
            counter.display()
        );
        let config = format!(
            "[[expansion]]\ntrigger = \":count\"\nreplacement = \"\"\n[expansion.command]\nprogram = \"/bin/sh\"\nargs = [\"-c\", {script:?}]\ncache_ms = 1000\n"
        );
        let mut engine = ExpansionEngine::new(Config::parse(&config).unwrap()).unwrap();
        let results = engine.process(InputEvent::Text(":count:count".into()));
        let _ = std::fs::remove_file(&counter);
        assert_eq!(results.len(), 2);
        assert_eq!(results[0].insert, "1");
        assert_eq!(results[1].insert, "1");
    }

    #[test]
    fn command_expansion_limits_are_validated_before_activation() {
        let config = r#"
            [[expansion]]
            trigger = ":bad-command"
            replacement = ""
            [expansion.command]
            program = "printf"
            timeout_ms = 5001
        "#;
        assert!(matches!(
            Config::parse(config),
            Err(ConfigError::InvalidCommand { .. })
        ));
    }

    #[test]
    fn malformed_config_is_an_error() {
        assert!(Config::parse("[[expansion]]\ntrigger = \":x\"\n").is_err());
    }

    #[test]
    fn engine_rejects_manually_constructed_invalid_config() {
        let config = Config {
            expansion: vec![crate::ExpansionConfig {
                trigger: String::new(),
                replacement: "value".into(),
                description: String::new(),
                tags: Vec::new(),
                category: String::new(),
                app_filter: Vec::new(),
                match_mode: MatchMode::Immediate,
                command: None,
                enabled: true,
                propagate_case: false,
            }],
            hotkey: Vec::new(),
            settings: crate::Settings::default(),
        };
        assert!(matches!(
            ExpansionEngine::new(config),
            Err(crate::ConfigError::EmptyTrigger { index: 0 })
        ));
    }

    #[test]
    fn nul_characters_are_rejected() {
        let trigger = r#"[[expansion]]
trigger = "a\u0000b"
replacement = "ok""#;
        assert!(matches!(
            Config::parse(trigger),
            Err(crate::ConfigError::NulCharacter {
                field: "trigger",
                ..
            })
        ));
        let replacement = r#"[[expansion]]
trigger = ":x"
replacement = "bad\u0000value""#;
        assert!(matches!(
            Config::parse(replacement),
            Err(crate::ConfigError::NulCharacter {
                field: "replacement",
                ..
            })
        ));
    }

    #[test]
    fn processes_each_character_in_a_chunk() {
        let mut engine = engine();
        let results = engine.process(InputEvent::Text("prefix :hello suffix".into()));
        assert_eq!(results.len(), 1);
        assert_eq!(results[0].trigger, ":hello");
    }

    #[test]
    fn expansion_results_are_bounded_per_text_event() {
        let config =
            Config::parse("[[expansion]]\ntrigger = \":x\"\nreplacement = \"ok\"").unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let results = engine.process(InputEvent::Text(":x".repeat(MAX_RESULTS_PER_EVENT + 1)));
        assert_eq!(results.len(), MAX_RESULTS_PER_EVENT);

        // Hitting the budget must not leave a partial trigger in the matcher.
        assert_eq!(engine.process(InputEvent::Text(":x".into())).len(), 1);
    }

    #[test]
    fn duplicate_triggers_are_rejected() {
        let config = "[[expansion]]\ntrigger = \":x\"\nreplacement = \"a\"\n[[expansion]]\ntrigger = \":x\"\nreplacement = \"b\"";
        assert!(matches!(
            Config::parse(config),
            Err(crate::ConfigError::DuplicateTrigger { .. })
        ));
    }

    #[test]
    fn prefix_triggers_use_the_longest_match() {
        let config = "[[expansion]]\ntrigger = \":h\"\nreplacement = \"a\"\n[[expansion]]\ntrigger = \":hello\"\nreplacement = \"b\"";
        let mut engine = ExpansionEngine::new(Config::parse(config).unwrap()).unwrap();
        let result = engine.process(InputEvent::Text(":hello".into()));
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].insert, "b");
    }

    #[test]
    fn short_prefix_waits_for_more_input_or_a_boundary() {
        let config = "[[expansion]]\ntrigger = \":h\"\nreplacement = \"short\"\n[[expansion]]\ntrigger = \":hello\"\nreplacement = \"long\"";
        let mut engine = ExpansionEngine::new(Config::parse(config).unwrap()).unwrap();
        assert!(engine.process(InputEvent::Text(":h".into())).is_empty());
        let result = engine.process(InputEvent::Text("x".into()));
        assert_eq!(result[0].insert, "short");

        assert!(engine.process(InputEvent::Text(":h".into())).is_empty());
        let result = engine.process(InputEvent::Boundary);
        assert_eq!(result[0].insert, "short");
    }

    #[test]
    fn word_boundary_mode_rejects_embedded_trigger() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":sig\"\nreplacement = \"signature\"\nmatch_mode = \"word-boundary\"",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert!(engine.process(InputEvent::Text("x:sig".into())).is_empty());
        assert_eq!(
            engine.process(InputEvent::Text(" :sig ".into()))[0].insert,
            "signature"
        );
    }

    /// Regression test: when `max_buffer_chars` is small enough that the
    /// character preceding a word-boundary trigger gets evicted from the
    /// buffer before the trigger finishes matching, the engine must fail
    /// closed (reject the match) rather than treat the evicted, unknown
    /// character as "no boundary violation".
    #[test]
    fn word_boundary_mode_fails_closed_when_buffer_truncates_preceding_context() {
        let config = || {
            Config::parse(
                "[settings]\nmax_buffer_chars = 4\n[[expansion]]\ntrigger = \":sig\"\nreplacement = \"signature\"\nmatch_mode = \"word-boundary\"",
            )
            .unwrap()
        };
        // "hello:sig" typed one character at a time: by the time ":sig" (4
        // chars) fills the 4-char buffer, the "o" that should block a
        // word-boundary match has already been evicted. Must still reject
        // rather than treat the unknown evicted character as a non-issue.
        let mut engine = ExpansionEngine::new(config()).unwrap();
        assert!(engine
            .process(InputEvent::Text("hello:sig".into()))
            .is_empty());
        // A real word boundary (nothing precedes the trigger at all) must
        // still match even with the same small buffer: this is the case
        // truncation must not be confused with. The trailing space is the
        // terminating character word-boundary mode needs to resolve the
        // match at all.
        let mut engine = ExpansionEngine::new(config()).unwrap();
        assert_eq!(
            engine.process(InputEvent::Text(":sig ".into()))[0].insert,
            "signature"
        );
    }

    #[test]
    fn word_boundary_mode_is_unicode_aware() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":sig\"\nreplacement = \"signature\"\nmatch_mode = \"word-boundary\"",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert!(engine.process(InputEvent::Text("é:sig".into())).is_empty());
        assert_eq!(
            engine.process(InputEvent::Text(" :sig ".into()))[0].insert,
            "signature"
        );
    }

    #[test]
    fn word_boundary_mode_waits_for_a_trailing_boundary() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":sig\"\nreplacement = \"signature\"\nmatch_mode = \"word-boundary\"",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert!(engine.process(InputEvent::Text(":sig".into())).is_empty());
        assert!(engine.process(InputEvent::Text("X".into())).is_empty());
        assert!(engine.process(InputEvent::Text(" :sig".into())).is_empty());
        assert_eq!(engine.process(InputEvent::Boundary)[0].insert, "signature");
    }

    struct RecordingInjector {
        calls: Vec<String>,
    }

    impl crate::TextInjector for RecordingInjector {
        fn name(&self) -> &'static str {
            "test"
        }

        fn erase(&mut self, trigger: &str) -> Result<(), crate::InjectorError> {
            self.calls.push(format!("erase:{trigger}"));
            Ok(())
        }

        fn insert(&mut self, text: &str) -> Result<(), crate::InjectorError> {
            self.calls.push(format!("insert:{text}"));
            Ok(())
        }
    }

    #[test]
    fn apply_erases_before_inserting() {
        let result = ExpansionResult {
            trigger: ":x".into(),
            erase_chars: 2,
            insert: "value".into(),
            cursor_offset: None,
        };
        let mut injector = RecordingInjector { calls: Vec::new() };
        ExpansionEngine::apply(&mut injector, &result).unwrap();
        assert_eq!(injector.calls, ["erase::x", "insert:value"]);
    }

    struct AtomicInjector {
        calls: Vec<String>,
    }

    impl crate::TextInjector for AtomicInjector {
        fn name(&self) -> &'static str {
            "atomic-test"
        }

        fn erase(&mut self, _: &str) -> Result<(), crate::InjectorError> {
            panic!("atomic backend should not use the default erase path")
        }

        fn insert(&mut self, _: &str) -> Result<(), crate::InjectorError> {
            panic!("atomic backend should not use the default insert path")
        }

        fn replace(&mut self, trigger: &str, text: &str) -> Result<(), crate::InjectorError> {
            self.calls.push(format!("replace:{trigger}:{text}"));
            Ok(())
        }
    }

    #[test]
    fn apply_uses_atomic_backend_operation_when_available() {
        let result = ExpansionResult {
            trigger: ":x".into(),
            erase_chars: 2,
            insert: "value".into(),
            cursor_offset: None,
        };
        let mut injector = AtomicInjector { calls: Vec::new() };
        ExpansionEngine::apply(&mut injector, &result).unwrap();
        assert_eq!(injector.calls, ["replace::x:value"]);
    }

    #[test]
    fn sensitive_focus_disables_matching_and_clears_buffer() {
        let mut engine = engine();
        assert!(engine.process(InputEvent::Text(":hel".into())).is_empty());
        engine.process(InputEvent::FocusChanged { sensitive: true });
        assert!(engine.process(InputEvent::Text("lo".into())).is_empty());
        engine.process(InputEvent::FocusChanged { sensitive: false });
        assert!(engine.process(InputEvent::Text(":hello".into())).len() == 1);
    }

    #[test]
    fn disabled_expansions_do_not_match() {
        let config = "[[expansion]]\ntrigger = \":off\"\nreplacement = \"secret\"\nenabled = false";
        let mut engine = ExpansionEngine::new(Config::parse(config).unwrap()).unwrap();
        assert!(engine.process(InputEvent::Text(":off".into())).is_empty());
    }

    #[test]
    fn disabled_prefix_does_not_block_enabled_expansion() {
        let config = r#"
            [[expansion]]
            trigger = ":x"
            replacement = "disabled"
            enabled = false

            [[expansion]]
            trigger = ":xyz"
            replacement = "enabled"
        "#;
        let mut engine = ExpansionEngine::new(Config::parse(config).unwrap()).unwrap();
        let result = engine.process(InputEvent::Text(":xyz".into()));
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].insert, "enabled");
    }

    #[test]
    fn disabled_duplicate_does_not_block_enabled_expansion() {
        let config = r#"
            [[expansion]]
            trigger = ":x"
            replacement = "disabled"
            enabled = false

            [[expansion]]
            trigger = ":x"
            replacement = "enabled"
        "#;
        let mut engine = ExpansionEngine::new(Config::parse(config).unwrap()).unwrap();
        let result = engine.process(InputEvent::Text(":x".into()));
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].insert, "enabled");
    }

    #[test]
    fn unknown_config_fields_are_rejected() {
        let config = "[[expansion]]\ntrigger = \":x\"\nreplacement = \"ok\"\nwat = true";
        assert!(Config::parse(config).is_err());
    }

    #[test]
    fn invalid_template_is_rejected_before_activation() {
        let config = "[[expansion]]\ntrigger = \":x\"\nreplacement = \"{{unknown}}\"";
        assert!(matches!(
            Config::parse(config),
            Err(crate::ConfigError::InvalidTemplate { .. })
        ));
    }

    #[test]
    fn oversized_replacements_are_rejected() {
        let config = format!(
            "[[expansion]]\ntrigger = \":x\"\nreplacement = \"{}\"",
            "a".repeat(1024 * 1024 + 1)
        );
        assert!(matches!(
            Config::parse(&config),
            Err(crate::ConfigError::ReplacementTooLarge { .. })
        ));
    }

    #[test]
    fn excessive_expansion_count_is_rejected() {
        let mut config = String::new();
        for index in 0..10_001 {
            config.push_str(&format!(
                "[[expansion]]\ntrigger = \":{index}\"\nreplacement = \"x\"\n"
            ));
        }
        assert!(matches!(
            Config::parse(&config),
            Err(crate::ConfigError::TooManyExpansions { .. })
        ));
    }

    #[test]
    fn oversized_configuration_is_rejected_before_parsing() {
        let config = "x".repeat(16 * 1024 * 1024 + 1);
        assert!(matches!(
            Config::parse(&config),
            Err(crate::ConfigError::ConfigTooLarge { .. })
        ));
    }

    #[test]
    fn non_regular_configuration_path_is_rejected() {
        let path =
            std::env::temp_dir().join(format!("wayexpand-config-directory-{}", std::process::id()));
        std::fs::create_dir(&path).unwrap();
        assert!(matches!(
            Config::load(&path),
            Err(crate::ConfigError::NotRegular { .. })
        ));
        std::fs::remove_dir(path).unwrap();
    }

    #[test]
    fn symlinked_configuration_validates_the_resolved_parent() {
        let root =
            std::env::temp_dir().join(format!("wayexpand-config-symlink-{}", std::process::id()));
        let target = root.join("target.toml");
        let link = root.join("link.toml");
        std::fs::create_dir(&root).unwrap();
        std::fs::write(
            &target,
            "[[expansion]]\ntrigger = \":x\"\nreplacement = \"ok\"\n",
        )
        .unwrap();
        // Set both modes explicitly rather than inheriting the umask: a
        // default of 002 (Debian/Ubuntu user-private-group setups) yields a
        // group-writable 0775 directory and 0664 file, which `Config::load`
        // correctly rejects, failing this test for the wrong reason.
        std::fs::set_permissions(&root, std::fs::Permissions::from_mode(0o700)).unwrap();
        std::fs::set_permissions(&target, std::fs::Permissions::from_mode(0o600)).unwrap();
        std::os::unix::fs::symlink(&target, &link).unwrap();
        assert!(Config::load(&link).is_ok());
        std::fs::remove_file(link).unwrap();
        std::fs::remove_file(target).unwrap();
        std::fs::remove_dir(root).unwrap();
    }

    #[test]
    fn fifo_configuration_path_is_rejected_without_blocking() {
        let path =
            std::env::temp_dir().join(format!("wayexpand-config-fifo-{}", std::process::id()));
        rustix::fs::mkfifoat(
            rustix::fs::CWD,
            &path,
            rustix::fs::Mode::from_raw_mode(0o600),
        )
        .unwrap();
        assert!(matches!(
            Config::load(&path),
            Err(crate::ConfigError::NotRegular { .. })
        ));
        std::fs::remove_file(path).unwrap();
    }

    #[test]
    fn group_writable_configuration_is_rejected() {
        let path = std::env::temp_dir().join(format!(
            "wayexpand-config-permissions-{}",
            std::process::id()
        ));
        std::fs::write(
            &path,
            "[[expansion]]\ntrigger = \":x\"\nreplacement = \"ok\"\n",
        )
        .unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o666)).unwrap();
        assert!(matches!(
            Config::load(&path),
            Err(crate::ConfigError::InsecurePermissions { .. })
        ));
        std::fs::remove_file(path).unwrap();
    }

    #[test]
    fn writable_non_sticky_configuration_parent_is_rejected() {
        let parent = std::env::temp_dir().join(format!(
            "wayexpand-config-parent-permissions-{}",
            std::process::id()
        ));
        let path = parent.join("expansions.toml");
        std::fs::create_dir(&parent).unwrap();
        std::fs::write(
            &path,
            "[[expansion]]\ntrigger = \":x\"\nreplacement = \"ok\"\n",
        )
        .unwrap();
        std::fs::set_permissions(&parent, std::fs::Permissions::from_mode(0o777)).unwrap();
        assert!(matches!(
            Config::load(&path),
            Err(crate::ConfigError::InsecureParent { .. })
        ));
        std::fs::set_permissions(&parent, std::fs::Permissions::from_mode(0o700)).unwrap();
        std::fs::remove_file(path).unwrap();
        std::fs::remove_dir(parent).unwrap();
    }

    #[test]
    fn excessive_enabled_trigger_data_is_rejected() {
        let mut config = String::new();
        for index in 0..=crate::config::MAX_TOTAL_TRIGGER_CHARS / 128 {
            config.push_str(&format!(
                "[[expansion]]\ntrigger = \":{index:08x}{}\"\nreplacement = \"x\"\n",
                "a".repeat(119)
            ));
        }
        assert!(matches!(
            Config::parse(&config),
            Err(crate::ConfigError::TriggerDataTooLarge { .. })
        ));
    }

    #[test]
    fn buffer_limit_is_bounded() {
        let config = "[settings]\nmax_buffer_chars = 0";
        assert!(matches!(
            Config::parse(config),
            Err(crate::ConfigError::InvalidBufferLimit)
        ));
    }

    #[test]
    fn buffer_limit_can_be_configured() {
        let config = "[settings]\nmax_buffer_chars = 2\n[[expansion]]\ntrigger = \":x\"\nreplacement = \"ok\"";
        let mut engine = ExpansionEngine::new(Config::parse(config).unwrap()).unwrap();
        assert_eq!(engine.process(InputEvent::Text("abc:x".into())).len(), 1);
    }

    #[test]
    fn propagate_case_leaves_replacement_unchanged_for_lowercase_trigger() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"\npropagate_case = true",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert_eq!(
            engine.process(InputEvent::Text(":sig".into()))[0].insert,
            "regards"
        );
    }

    #[test]
    fn propagate_case_uppercases_replacement_for_uppercase_trigger() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"\npropagate_case = true",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert_eq!(
            engine.process(InputEvent::Text(":SIG".into()))[0].insert,
            "REGARDS"
        );
    }

    #[test]
    fn propagate_case_capitalizes_replacement_for_capitalized_trigger() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"\npropagate_case = true",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert_eq!(
            engine.process(InputEvent::Text(":Sig".into()))[0].insert,
            "Regards"
        );
    }

    #[test]
    fn propagate_case_works_with_word_boundary_mode() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"\nmatch_mode = \"word-boundary\"\npropagate_case = true",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert_eq!(
            engine.process(InputEvent::Text(" :SIG ".into()))[0].insert,
            "REGARDS"
        );
    }

    #[test]
    fn propagate_case_is_opt_in_and_does_not_affect_ordinary_triggers() {
        // Without `propagate_case`, matching stays strictly literal:
        // typing the trigger in a different case must not match at all.
        let config =
            Config::parse("[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"").unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        assert!(engine.process(InputEvent::Text(":SIG".into())).is_empty());
        assert_eq!(
            engine.process(InputEvent::Text(":sig".into()))[0].insert,
            "regards"
        );
    }

    #[test]
    fn cursor_marker_splits_replacement_and_reports_trailing_length() {
        let config =
            Config::parse("[[expansion]]\ntrigger = \":paren\"\nreplacement = \"(){{cursor}}!\"")
                .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let result = engine.process(InputEvent::Text(":paren".into()))[0].clone();
        assert_eq!(result.insert, "()!");
        // "!" is the one character after the marker, so the cursor should
        // land between "(" and ")": one character back from the end.
        assert_eq!(result.cursor_offset, Some(1));
    }

    #[test]
    fn cursor_marker_is_optional_and_defaults_to_end_of_text() {
        let config =
            Config::parse("[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"").unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let result = engine.process(InputEvent::Text(":sig".into()))[0].clone();
        assert_eq!(result.insert, "regards");
        assert_eq!(result.cursor_offset, None);
    }

    #[test]
    fn cursor_marker_works_alongside_other_template_variables() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":hi\"\nreplacement = \"Hi {{cursor}}, {{username}}!\"",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let result = engine.process(InputEvent::Text(":hi".into()))[0].clone();
        let expected_tail = format!(", {}!", crate::TemplateContext::system().username);
        assert_eq!(result.insert, format!("Hi {expected_tail}"));
        assert_eq!(result.cursor_offset, Some(expected_tail.chars().count()));
    }

    #[test]
    fn cursor_marker_is_not_recognized_in_command_output() {
        let config = Config::parse(
            "[[expansion]]\ntrigger = \":cmd\"\nreplacement = \"fallback\"\n[expansion.command]\nprogram = \"printf\"\nargs = [\"literal {{cursor}} text\"]",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let result = engine.process(InputEvent::Text(":cmd".into()))[0].clone();
        assert_eq!(result.insert, "literal {{cursor}} text");
        assert_eq!(result.cursor_offset, None);
    }

    #[test]
    fn undo_reverts_the_expansion_immediately_following_it() {
        let config = Config::parse(
            "[settings]\nundo_chord = \"Ctrl+Z\"\n[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        let expansion = engine.process(InputEvent::Text(":sig".into()))[0].clone();
        assert_eq!(expansion.insert, "regards");
        let undo = engine
            .try_undo(&KeyChord::parse("Ctrl+Z").unwrap())
            .expect("an expansion is pending to undo");
        // Erases the full inserted replacement and types the original
        // trigger back.
        assert_eq!(undo.erase_chars, "regards".chars().count());
        assert_eq!(undo.insert, ":sig");
    }

    #[test]
    fn undo_is_a_one_shot_and_does_nothing_without_a_pending_expansion() {
        let config = Config::parse(
            "[settings]\nundo_chord = \"Ctrl+Z\"\n[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        engine.process(InputEvent::Text(":sig".into()));
        let chord = KeyChord::parse("Ctrl+Z").unwrap();
        assert!(engine.try_undo(&chord).is_some());
        // A second press right after has nothing left to undo.
        assert!(engine.try_undo(&chord).is_none());
    }

    #[test]
    fn undo_is_invalidated_by_any_typing_in_between() {
        let config = Config::parse(
            "[settings]\nundo_chord = \"Ctrl+Z\"\n[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        engine.process(InputEvent::Text(":sig".into()));
        engine.process(InputEvent::Text("x".into()));
        assert!(engine
            .try_undo(&KeyChord::parse("Ctrl+Z").unwrap())
            .is_none());
    }

    #[test]
    fn undo_is_disabled_when_not_configured() {
        let config =
            Config::parse("[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"").unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        engine.process(InputEvent::Text(":sig".into()));
        assert!(engine
            .try_undo(&KeyChord::parse("Ctrl+Z").unwrap())
            .is_none());
    }

    #[test]
    fn undo_does_not_apply_to_a_cursor_marker_expansion() {
        let config = Config::parse(
            "[settings]\nundo_chord = \"Ctrl+Z\"\n[[expansion]]\ntrigger = \":paren\"\nreplacement = \"(){{cursor}}\"",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        engine.process(InputEvent::Text(":paren".into()));
        assert!(engine
            .try_undo(&KeyChord::parse("Ctrl+Z").unwrap())
            .is_none());
    }

    #[test]
    fn undo_restores_the_case_variant_actually_typed() {
        let config = Config::parse(
            "[settings]\nundo_chord = \"Ctrl+Z\"\n[[expansion]]\ntrigger = \":sig\"\nreplacement = \"regards\"\npropagate_case = true",
        )
        .unwrap();
        let mut engine = ExpansionEngine::new(config).unwrap();
        engine.process(InputEvent::Text(":SIG".into()));
        let undo = engine
            .try_undo(&KeyChord::parse("Ctrl+Z").unwrap())
            .unwrap();
        assert_eq!(undo.insert, ":SIG");
    }
}
